version: "3"
services:
    back-end:
        container_name: springboot-app
        build:
            context: back-end
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        restart: always
        environment:
            DB_URL: jdbc:mysql://mysql-db/music_db
            DB_USERNAME: unseenuser
            DB_PASSWORD: godblessyou
        depends_on:
            - mysql-db
        networks:
            - frontend
            - backend
    front-end:
        container_name: react-app
        build:
            context: front-end
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        restart: always
        depends_on: 
            - back-end
        networks:
            - frontend
    mysql-db:
        container_name: mysql-db
        image: mysql:8.0.12
        volumes: 
            - dbdata:/var/lib/mysql
        restart: always
        environment:
            MYSQL_DATABASE: music_db
            MYSQL_USER: unseenuser
            MYSQL_PASSWORD: godblessyou
            MYSQL_ROOT_PASSWORD: godblessyou
        networks:
            - backend
volumes:
    dbdata:
networks:
    backend:
    frontend:
